apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinatra-app
  template:
    metadata:
      labels:
        app: sinatra-app
    spec:
      containers:
      - name: sinatra-app
        image: appsignal/kubetest:latest
        env:
          - name: APPSIGNAL_ACTIVE
            value: "true"
          - name: APPSIGNAL_APP_NAME
            value: "kubetest"
          - name: APPSIGNAL_APP_ENV
            value: "development"
          - name: APPSIGNAL_PUSH_API_KEY
            value: "00000000-0000-0000-0000-000000000000"
          - name: APPSIGNAL_LOG
            value: "stdout"
        ports:
          - containerPort: 4567
