apiVersion: v1
kind: Service
metadata:
  name: kubernetes-rails-example-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: sinatra-app
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
      name: http
